### ISSUE TITLE
Issue with Load options

### ISSUE THREAD

**Issue by malerisch** [bytebutcher/burp-send-to#3]
Hi,
First, very nice extension! I was giving it a try and since I use multiple burp instances (different laptops), I need to be able to export/import the entries - so I save via the options, and I see indeed a file which contains all the references to the entries I created. However, when I try to import it back, it doesn't work - no error is returned in the extension output tab.
Thanks.

**Comment by bytebutcher** [comment]
Hi malerisch, thanks for reporting this issue. Could you upload an example file which illustrates this issue? Do you have the same version of the "Send To" Extension installed on both laptops?

**Comment by osamahamad** [comment]
Hi @malerisch @bytebutcher , The same happen on my side regarding the following version : burp-send-to-extension 1.5b

Tested on burpsuite professional + community edition. 


2 Computer, Save configuration from first one and try to load it on the second PC, The entries will not come and no error occur. 
Same version of the extension on both computers has been installed.


Example configuration file : 
[burp-send-to-lab-options.zip](https://github.com/bytebutcher/burp-send-to/files/5824299/burp-send-to-lab-options.zip)

**Comment by bytebutcher** [comment]
Hi @osamahamad, thanks for the example configuration. I was able to reproduce and hunt down the issue. I uploaded a new version (see [burp-send-to-extension-1.5.jar](https://github.com/bytebutcher/burp-send-to/releases/download/v1.5/burp-send-to-extension-1.5.jar) which should fix the error (it also includes the changes from 1.5b).

**Comment by osamahamad** [comment]
Hello @bytebutcher, I just tested it but it throw the following on Burp Error windows. 

It does not able to add on burp suite community edition + pro

```

java.lang.NullPointerException
	at net.bytebutcher.burpsendtoextension.gui.SendToTab.<init>(SendToTab.java:128)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at burp.c9f.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)

```

**Comment by bytebutcher** [comment]
Sorry about that. I realised just after uploading the new release that the UI changes were not added to the .jar file.
I've rebuild the project and the jar file should now work again!

**Comment by bytebutcher** [comment]
Please reopen, when issue still persists!
